spring:
  profiles:
    active: dev # dev 아니면 prod

  config:
    import: optional:classpath:application-API-KEY.properties

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  servlet:
    encoding:
      force-response: true

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

slack:
  token: ${SLACK_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

jwt:
  secret: ${JWT_CODE}
  expiration: 3600000 # 1시간

admin:
  password: ${ADMIN_PASSWORD}