spring:
  config:
    import: optional:classpath:application-API-KEY.properties
  datasource:
#    url: jdbc:mysql://${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  servlet:
    encoding:
      force-response: true

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

slack:
  token: ${SLACK_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}