spring:
  config:
    import: optional:classpath:application-API-KEY.properties

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: minseok
    password: 1919

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    encoding:
      force-response: true

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

slack:
  token: ${SLACK_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

jwt:
  secret: ${JWT_CODE}
  expiration: 3600000 # 1시간

admin:
  password: ${ADMIN_PASSWORD}